# Generated by Django 5.1.1 on 2024-09-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='products',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='products_supplied',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='InventoryMovement',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
