# Generated by Django 5.1.1 on 2024-09-26 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('product', '0001_initial'),
        ('warehouse', '0002_remove_order_customer_remove_order_ordered_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_products',
            field=models.ManyToManyField(to='product.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.shipment'),
        ),
    ]
